### ISSUE TITLE
bug: Selecting state tab multiple times results in duplicate images/videos divs

### ISSUE THREAD

**Issue by sautumn** [ubershmekel/2020PoliceBrutality#5]
## Expected Behavior

Clicking state tab multiple times does nothing as state is already selected.

## Current Behavior

Clicking a state tab twice results in duplicate image/videos in the link section. Each click appends a new div.

## Possible Solution

Disable clicks for already selected states

## Steps to Reproduce

1. Click a state tab
2. Click state tab again.
3. See new div being appended/content duplicated.

**Comment by ubershmekel** [comment]
Thank you for this!
